[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild" 

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/api/netlify-forms"
  to = "/.netlify/functions/submission-created"
  status = 200 